# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus:
google_analytics:
title: cobe's blog

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: 코딩하는베짱이

description: Stylish Jekyll Theme
author:
  name: 코딩하는베짱이
  email: kown8447@naver.com
  github: kown8447
  twitter: kown8447
  pinterest: 
  linkedin: 
  bio: 베짱이의 일상, 기술 블로그
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html


# set it as url of an image
sidebar_background_image: https://lh3.googleusercontent.com/xAIiHQNFZKIL7tlgXOiIZABpL43vj-oCeRm-ORUyAIQoADIM0fI2VGomjzpAf_eXWSWnVYPXzdMu0aoRSpzT8GLREd_IayiQDMaHMsfelTZgrphfJPMvwUsVZSWekMfEaVvzW26QwWCFNngLU4eOaTmSVjTVZGjaIu9FHLsNaGhQy0o4hRcE3_RiqbSPfp3KBf7d9eg4vZxIB2U_tMk_t1KZffK-9YRhYk0xAlSTyEB7w43nS3-N4cBak8urbBSdPIbxQfF0LnSLbleVqhV0d9O2Y-CzJfhLedQUj-RGPbsRgwWpy0l59oPR5SQ6Deje0Ot_atumEPJTesKlcoYyJsjTK_0PwrYcnqvrmLRiOroUEujjdVeGhSH8hTQ9WBFvMfHJ7Fcqc9WZofsF2wpNKuRtewsyXwrc4FerQHWt3bPbYjvyDr6uyrAXzpiivFBCzyKJ0XGdiyi3Xbzd8YSsuRCcjd9mnhfmd80iTy-H7rSErjq_bt0FJ10LJvBTdiQZjQEBBQJlSRWZsokDwkjBDjt0PA2FIcynt9fgDWZrD8ODdNiHnH8PGsEADhBYr4XlfRnQP4M5ypDMh3g-VF9CeHRDbnt8HOmKVFrpN7trmyBcDWVWEsb6rmoWtdYGuKIUqBM4Dt85cQid4rKPCnvm1Nh63LyNuKgPiadPlQtaXc93rhjIQanI8zFkTCw1=w1920-h1280-no?authuser=0

BASE_PATH:

plugins:
  - jekyll-paginate
