# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: 코딩하는 베짱이
google_analytics: 코딩하는 베짱이
title: cobe's blog

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: 코딩하는 베짱이

description: Stylish Jekyll Theme
author:
  name: 코딩하는 베짱이
  email: kown8447@naver.com
  github: kown8447
  twitter: kown8447
  pinterest: 
  linkedin: 
  bio: 베짱이의 일상, 기술 기록 블로그
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
